/* This Proc Format program was automatically generated by Stat/Transfer ver.14.3.1160.0717 */

/* ENCODING CP1252 */



libname library '' ;

proc format library = library ;
   value P_PANEL
      1 = 'ABS'  
      2 = 'Amerispeak' ;
   value P_GEO
      1 = '(1) California'  
      2 = '(2) Colorado'  
      3 = '(3) Florida'  
      4 = '(4) Louisiana'  
      5 = '(5) Minnesota'  
      6 = '(6) Missouri'  
      7 = '(7) Montana'  
      8 = '(8) New York'  
      9 = '(9) Oregon'  
      10 = '(10) Texas'  
      11 = '(11) Atlanta-Sandy Springs-Alpharetta, Georgia'  
      12 = '(12) Baltimore-Columbia-Towson, Maryland'  
      13 = '(13) Birmingham-Hoover, Alabama'  
      14 = '(14) Chicago-Naperville-Elgin, Illinois-Indiana-Wisconsin'  
      15 = '(15) Cleveland-Elyria, Ohio'  
      16 = '(16) Columbus, Ohio'  
      17 = '(17) Phoenix-Mesa-Chandler, Arizona'  
      18 = '(18) Pittsburgh, Pennsylvania' ;
   value SOC1F
      1 = '(1) All'  
      2 = '(2) Most'  
      3 = '(3) Some'  
      4 = '(4) None'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC2A
      1 = '(1) Basically every day'  
      2 = '(2) A few times a week'  
      3 = '(3) A few times a month'  
      4 = '(4) Once a month'  
      5 = '(5) Not at all'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC2B
      1 = '(1) Basically every day'  
      2 = '(2) A few times a week'  
      3 = '(3) A few times a month'  
      4 = '(4) Once a month'  
      5 = '(5) Not at all'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC3A
      1 = '(1) Basically every day'  
      2 = '(2) A few times a week'  
      3 = '(3) A few times a month'  
      4 = '(4) Once a month'  
      5 = '(5) Not at all'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC3B
      1 = '(1) Basically every day'  
      2 = '(2) A few times a week'  
      3 = '(3) A few times a month'  
      4 = '(4) Once a month'  
      5 = '(5) Not at all'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC4A
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC4B
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS8F
      1 = '(1) Excellent'  
      2 = '(2) Very good'  
      3 = '(3) Good'  
      4 = '(4) Fair'  
      5 = '(5) Poor'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1A
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1B
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1C
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1D
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1E
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1G
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1H
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1I
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1J
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1K
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1L
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1M
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1N
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1O
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1P
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS1Q
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC5A
      1 = '(1) Not at all or less than 1 day'  
      2 = '(2) 1-2 days'  
      3 = '(3) 3-4 days'  
      4 = '(4) 5-7 days'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC5B
      1 = '(1) Not at all or less than 1 day'  
      2 = '(2) 1-2 days'  
      3 = '(3) 3-4 days'  
      4 = '(4) 5-7 days'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC5C
      1 = '(1) Not at all or less than 1 day'  
      2 = '(2) 1-2 days'  
      3 = '(3) 3-4 days'  
      4 = '(4) 5-7 days'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC5D
      1 = '(1) Not at all or less than 1 day'  
      2 = '(2) 1-2 days'  
      3 = '(3) 3-4 days'  
      4 = '(4) 5-7 days'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value SOC5E
      1 = '(1) Not at all or less than 1 day'  
      2 = '(2) 1-2 days'  
      3 = '(3) 3-4 days'  
      4 = '(4) 5-7 days'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS2_1F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_2F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_3F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_4F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_5F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_6F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_7F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_8F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_9F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_10F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_11F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_12F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_13F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_14F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_15F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_16F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_17F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_18F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_19F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_DK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_SK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS2_RE
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS10A
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Already done this'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS10B
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Already done this'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS10C
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Already done this'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS10D
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Already done this'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS10E
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Already done this'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8A
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8B
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8C
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8D
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8E
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8G
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8H
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8I
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8J
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8K
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8L
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8M
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8N
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8O
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8P
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8Q
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8R
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON8S
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON7_1F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_2F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_3F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_4F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_5F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_6F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_7F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_8F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_DK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_SK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON7_RE
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value ECON1F
      1 = '(1) Yes, I worked for someone else for wages, salary, piece'  
      2 = '(2) Yes, I worked as self-employed in my own business, profe'  
      3 = '(3) No, I did not work for pay last week.'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON2F
      777 = '(777) DON''T KNOW'  
      998 = '(998) SKIPPED ON WEB'  
      999 = '(999) REFUSED' ;
   value ECON4F
      1 = '(1) I do not want to be employed at this time'  
      2 = '(2) I am retired'  
      3 = '(3) I was laid-off temporarily or furloughed'  
      4 = '(4) I was not at my usual jobs because I was caring for chil'  
      5 = '(5) I was not at my usual jobs because I was caring for an e'  
      6 = '(6) I was not at my usual jobs because I was caring for some'  
      7 = '(7) I was not at my usual jobs because I was recovering from'  
      8 = '(8) I was unemployed but looking for work since before March'  
      9 = '(9) I was unemployed and began looking for work after March'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON3F
      777 = '(777) DON''T KNOW'  
      998 = '(998) SKIPPED ON WEB'  
      999 = '(999) REFUSED' ;
   value ECON4A
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON4B
      1 = '(1) Extremely likely'  
      2 = '(2) Very likely'  
      3 = '(3) Moderately likely'  
      4 = '(4) Not too likely'  
      5 = '(5) Not likely at all'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6A
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6B
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6C
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6D
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6E
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6F
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6G
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6H
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6I
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6J
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6K
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON6L
      1 = '(1) Received'  
      2 = '(2) Applied for'  
      3 = '(3) Tried to apply for'  
      4 = '(4) Did not receive nor apply for any'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON5A_A
      1 = '(1) Often true'  
      2 = '(2) Sometimes true'  
      3 = '(3) Never true'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value ECON5A_B
      1 = '(1) Often true'  
      2 = '(2) Sometimes true'  
      3 = '(3) Never true'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS7_1F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_2F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_3F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_4F
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_DK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_SK
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS7_RE
      0 = '(0) No'  
      1 = '(1) Yes' ;
   value PHYS11F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS11_T
      777 = '(777) DON''T KNOW'  
      888 = '(888) OUT OF RANGE'  
      998 = '(998) SKIPPED ON WEB'  
      999 = '(999) REFUSED' ;
   value PHYS9A
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9B
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9C
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9D
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9E
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9G
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS9H
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3A
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3B
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3C
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3D
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3E
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3G
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3H
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3I
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3J
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3K
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3L
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS3M
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS4F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS5F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value PHYS6F
      1 = '(1) Yes'  
      2 = '(2) No'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value AGE4F
      1 = '(1) 18-29'  
      2 = '(2) 30-44'  
      3 = '(3) 45-59'  
      4 = '(4) 60+'  
      99 = '(99) Under 18' ;
   value AGE7F
      1 = '(1) 18-24'  
      2 = '(2) 25-34'  
      3 = '(3) 35-44'  
      4 = '(4) 45-54'  
      5 = '(5) 55-64'  
      6 = '(6) 65-74'  
      7 = '(7) 75+'  
      99 = '(99) Under 18' ;
   value GENDER
      0 = '(0) Unknown'  
      1 = '(1) Male'  
      2 = '(2) Female'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value RACETH
      1 = '(1) White, non-Hispanic'  
      2 = '(2) Black, non-Hispanic'  
      3 = '(3) Hispanic'  
      4 = '(4) Other, non-Hispanic'  
      77 = '(77) DON''T KNOW'  
      88 = '(88) Removed for disclosure risk'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value RACE_R2F
      1 = '(1) White non-Hispanic'  
      2 = '(2) Nonwhite'  
      77 = '(77) DONT KNOW'  
      88 = '(88) Removed for disclosure risk'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99)REFUSED' ;
   value HHINCOME
      1 = 'Under $10,000'  
      2 = '$10,000 to under $20,000'  
      3 = '$20,000 to under $30,000'  
      4 = '$30,000 to under $40,000'  
      5 = '$40,000 to under $50,000'  
      6 = '$50,000 to under $75,000'  
      7 = '$75,000 to under $100,000'  
      8 = '$100,000 to under $150,000'  
      9 = '$150,000 or more'  
      77 = 'DON''T KNOW'  
      98 = 'SKIPPED ON WEB'  
      99 = 'REFUSED' ;
   value EDUCATIO
      1 = '(1) No HS diploma'  
      2 = '(2) HIGH SCHOOL GRADUATE - high school DIPLOMA or the equiva'  
      3 = '(3) Some college, no degree'  
      4 = '(4) Associate degree'  
      5 = '(5) Bachelors degree'  
      6 = '(6) Masters degree'  
      7 = '(7) Professional or Doctorate degree'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value EDUC4F
      1 = '(1) No HS diploma'  
      2 = '(2) HS graduate or equivalent'  
      3 = '(3) Some college'  
      4 = '(4) BA or above'  
      77 = '(77) Not sure'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value P_OCCUPY
      1 = '(1) Arts, Design, Entertainment, Sports, and Media Occupatio'  
      2 = '(2) Community and Social Service Occupations'  
      3 = '(3) Healthcare Support Occupations'  
      4 = '(4) Installation, Maintenance, and Repair Occupations'  
      5 = '(5) Architecture and Engineering Occupations'  
      6 = '(6) Construction and Extraction Occupations'  
      7 = '(7) Production Occupations'  
      8 = '(8) Building and Grounds Cleaning and Maintenance Occupation'  
      9 = '(9) Healthcare Practitioners and Technical Occupations'  
      10 = '(10) Life, Physical, and Social Science Occupations'  
      11 = '(11) Protective Service Occupations'  
      12 = '(12) Personal Care and Service Occupations'  
      13 = '(13) Computer and Mathematical Occupations'  
      14 = '(14) Sales and Related Occupations'  
      15 = '(15) Education, Training, and Library Occupations'  
      16 = '(16) Office and Administrative Support Occupations'  
      17 = '(17) Food Preparation and Serving Related Occupations'  
      18 = '(18) Legal Occupations'  
      19 = '(19) Farming, Fishing, and Forestry Occupations'  
      20 = '(20) Business and Financial Operations Occupations'  
      21 = '(21) Management Occupations'  
      22 = '(22) Transportation and Material Moving Occupations'  
      23 = '(23) Military Specific Occupations'  
      24 = '(24) Other (please specify)'  
      25 = '(25) Have never worked'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HHSIZE1F
      1 = '(1) One person, I live by myself'  
      2 = '(2) Two persons'  
      3 = '(3) Three persons'  
      4 = '(4) Four persons'  
      5 = '(5) Five persons'  
      6 = '(6) Six or more persons'  
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HH01S
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HH25S
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HH612S
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HH1317S
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value HH18OVS
      77 = '(77) DON''T KNOW'  
      98 = '(98) SKIPPED ON WEB'  
      99 = '(99) REFUSED' ;
   value REGION4F
      1 = '(1) Northeast'  
      2 = '(2) Midwest'  
      3 = '(3) South'  
      4 = '(4) West' ;
   value REGION9F
      1 = '(1) New England'  
      2 = '(2) Mid-Atlantic'  
      3 = '(3) East North Central'  
      4 = '(4) West North Central'  
      5 = '(5) South Atlantic'  
      6 = '(6) East South Central'  
      7 = '(7) West South Central'  
      8 = '(8) Mountain'  
      9 = '(9) Pacific' ;
   value P_DENSE
      1 = '(1) Rural'  
      2 = '(2) Suburban'  
      3 = '(3) Urban' ;
   value MODE
      1 = '(1) Phone interview'  
      2 = '(2) Web Interview' ;
   value LANGUAGE
      1 = '(1) English'  
      2 = '(2) Spanish' ;
   value MAIL50F
      1 = '(1) 4/20/2020'  
      2 = '(2) 4/21/2020'  
      3 = '(3) 4/22/2020'  
      4 = '(4) 4/23/2020' ;
   value RACE1_BA
      1 = '(1) NH white 5'  
      2 = '(2) NH black 5'  
      3 = '(3) Hispanic 5'  
      4 = '(4) NH Asian 5'  
      5 = '(5) NH Other 5'  
      88 = '(88) Removed for disclosure risk' ;
   value RACE2_BA
      1 = '(1) NH white'  
      2 = '(2) NH black'  
      3 = '(3) Hispanic'  
      4 = '(4) NH AIAN + PI'  
      5 = '(5) NH Chinese'  
      6 = '(6) NH Asian Indian'  
      7 = '(7) NH Filipino + Vietnamese'  
      8 = '(8) NH Japanese + Korean'  
      9 = '(9) NH Other' ;
   value INC_BANN
      1 = '(1) Less than $30,000'  
      2 = '(2) $30k to less than $60k'  
      3 = '(3) $60k to less than $125k'  
      4 = '(4) More than $125k' ;
   value AGE_BANN
      1 = '(1) 18-22'  
      2 = '(2) 23-64'  
      3 = '(3) 65+' ;
   value HH_BANNE
      1 = '(1) Alone'  
      2 = '(2) +1 other adult only'  
      3 = '(3) 1 or 2 kids'  
      4 = '(4) 3 or more kids'  
      5 = '(5) Other' ;

proc datasets library = library ;
modify covid_w1_delivered;
   format   P_PANEL P_PANEL.;
   format     P_GEO P_GEO.;
   format      SOC1 SOC1F.;
   format     SOC2A SOC2A.;
   format     SOC2B SOC2B.;
   format     SOC3A SOC3A.;
   format     SOC3B SOC3B.;
   format     SOC4A SOC4A.;
   format     SOC4B SOC4B.;
   format     PHYS8 PHYS8F.;
   format    PHYS1A PHYS1A.;
   format    PHYS1B PHYS1B.;
   format    PHYS1C PHYS1C.;
   format    PHYS1D PHYS1D.;
   format    PHYS1E PHYS1E.;
   format    PHYS1F PHYS1F.;
   format    PHYS1G PHYS1G.;
   format    PHYS1H PHYS1H.;
   format    PHYS1I PHYS1I.;
   format    PHYS1J PHYS1J.;
   format    PHYS1K PHYS1K.;
   format    PHYS1L PHYS1L.;
   format    PHYS1M PHYS1M.;
   format    PHYS1N PHYS1N.;
   format    PHYS1O PHYS1O.;
   format    PHYS1P PHYS1P.;
   format    PHYS1Q PHYS1Q.;
   format     SOC5A SOC5A.;
   format     SOC5B SOC5B.;
   format     SOC5C SOC5C.;
   format     SOC5D SOC5D.;
   format     SOC5E SOC5E.;
   format   PHYS2_1 PHYS2_1F.;
   format   PHYS2_2 PHYS2_2F.;
   format   PHYS2_3 PHYS2_3F.;
   format   PHYS2_4 PHYS2_4F.;
   format   PHYS2_5 PHYS2_5F.;
   format   PHYS2_6 PHYS2_6F.;
   format   PHYS2_7 PHYS2_7F.;
   format   PHYS2_8 PHYS2_8F.;
   format   PHYS2_9 PHYS2_9F.;
   format  PHYS2_10 PHYS2_10F.;
   format  PHYS2_11 PHYS2_11F.;
   format  PHYS2_12 PHYS2_12F.;
   format  PHYS2_13 PHYS2_13F.;
   format  PHYS2_14 PHYS2_14F.;
   format  PHYS2_15 PHYS2_15F.;
   format  PHYS2_16 PHYS2_16F.;
   format  PHYS2_17 PHYS2_17F.;
   format  PHYS2_18 PHYS2_18F.;
   format  PHYS2_19 PHYS2_19F.;
   format  PHYS2_DK PHYS2_DK.;
   format PHYS2_SKP PHYS2_SK.;
   format PHYS2_REF PHYS2_RE.;
   format   PHYS10A PHYS10A.;
   format   PHYS10B PHYS10B.;
   format   PHYS10C PHYS10C.;
   format   PHYS10D PHYS10D.;
   format   PHYS10E PHYS10E.;
   format    ECON8A ECON8A.;
   format    ECON8B ECON8B.;
   format    ECON8C ECON8C.;
   format    ECON8D ECON8D.;
   format    ECON8E ECON8E.;
   format    ECON8F ECON8F.;
   format    ECON8G ECON8G.;
   format    ECON8H ECON8H.;
   format    ECON8I ECON8I.;
   format    ECON8J ECON8J.;
   format    ECON8K ECON8K.;
   format    ECON8L ECON8L.;
   format    ECON8M ECON8M.;
   format    ECON8N ECON8N.;
   format    ECON8O ECON8O.;
   format    ECON8P ECON8P.;
   format    ECON8Q ECON8Q.;
   format    ECON8R ECON8R.;
   format    ECON8S ECON8S.;
   format   ECON7_1 ECON7_1F.;
   format   ECON7_2 ECON7_2F.;
   format   ECON7_3 ECON7_3F.;
   format   ECON7_4 ECON7_4F.;
   format   ECON7_5 ECON7_5F.;
   format   ECON7_6 ECON7_6F.;
   format   ECON7_7 ECON7_7F.;
   format   ECON7_8 ECON7_8F.;
   format  ECON7_DK ECON7_DK.;
   format ECON7_SKP ECON7_SK.;
   format ECON7_REF ECON7_RE.;
   format     ECON1 ECON1F.;
   format     ECON2 ECON2F.;
   format     ECON4 ECON4F.;
   format     ECON3 ECON3F.;
   format    ECON4A ECON4A.;
   format    ECON4B ECON4B.;
   format    ECON6A ECON6A.;
   format    ECON6B ECON6B.;
   format    ECON6C ECON6C.;
   format    ECON6D ECON6D.;
   format    ECON6E ECON6E.;
   format    ECON6F ECON6F.;
   format    ECON6G ECON6G.;
   format    ECON6H ECON6H.;
   format    ECON6I ECON6I.;
   format    ECON6J ECON6J.;
   format    ECON6K ECON6K.;
   format    ECON6L ECON6L.;
   format  ECON5A_A ECON5A_A.;
   format  ECON5A_B ECON5A_B.;
   format   PHYS7_1 PHYS7_1F.;
   format   PHYS7_2 PHYS7_2F.;
   format   PHYS7_3 PHYS7_3F.;
   format   PHYS7_4 PHYS7_4F.;
   format  PHYS7_DK PHYS7_DK.;
   format PHYS7_SKP PHYS7_SK.;
   format PHYS7_REF PHYS7_RE.;
   format    PHYS11 PHYS11F.;
   format PHYS11_TEMP PHYS11_T.;
   format    PHYS9A PHYS9A.;
   format    PHYS9B PHYS9B.;
   format    PHYS9C PHYS9C.;
   format    PHYS9D PHYS9D.;
   format    PHYS9E PHYS9E.;
   format    PHYS9F PHYS9F.;
   format    PHYS9G PHYS9G.;
   format    PHYS9H PHYS9H.;
   format    PHYS3A PHYS3A.;
   format    PHYS3B PHYS3B.;
   format    PHYS3C PHYS3C.;
   format    PHYS3D PHYS3D.;
   format    PHYS3E PHYS3E.;
   format    PHYS3F PHYS3F.;
   format    PHYS3G PHYS3G.;
   format    PHYS3H PHYS3H.;
   format    PHYS3I PHYS3I.;
   format    PHYS3J PHYS3J.;
   format    PHYS3K PHYS3K.;
   format    PHYS3L PHYS3L.;
   format    PHYS3M PHYS3M.;
   format     PHYS4 PHYS4F.;
   format     PHYS5 PHYS5F.;
   format     PHYS6 PHYS6F.;
   format      AGE4 AGE4F.;
   format      AGE7 AGE7F.;
   format    GENDER GENDER.;
   format    RACETH RACETH.;
   format   RACE_R2 RACE_R2F.;
   format  HHINCOME HHINCOME.;
   format EDUCATION EDUCATIO.;
   format     EDUC4 EDUC4F.;
   format P_OCCUPY2 P_OCCUPY.;
   format   HHSIZE1 HHSIZE1F.;
   format     HH01S HH01S.;
   format     HH25S HH25S.;
   format    HH612S HH612S.;
   format   HH1317S HH1317S.;
   format   HH18OVS HH18OVS.;
   format   REGION4 REGION4F.;
   format   REGION9 REGION9F.;
   format   P_DENSE P_DENSE.;
   format      MODE MODE.;
   format  LANGUAGE LANGUAGE.;
   format    MAIL50 MAIL50F.;
   format RACE1_BANNER RACE1_BA.;
   format RACE2_BANNER RACE2_BA.;
   format INC_BANNER INC_BANN.;
   format AGE_BANNER AGE_BANN.;
   format HH_BANNER HH_BANNE.;
quit;
